### ISSUE TITLE
No longer functional as of Foundry v9

### ISSUE THREAD

**Issue by GambetTV** [cswendrowski/FoundryVTT-Drag-Upload#37]
Title says it all, this module no longer works. This is one of my most vital modules, so I hope you find the time to update it! Thank you.

**Comment by Glunty** [comment]
Error is on dragupload.js:98
Uncaught (in promise) TypeError: CONST.AUDIO_FILE_EXTENSIONS.filter is not a function
[Detected 1 package: dragupload]
    at handleDrop (dragupload.js:98)
    at DragDrop.callback (foundry.js:44100)
    at DragDrop._handleDrop (foundry.js:44151)
handleDrop @ dragupload.js:98
callback @ foundry.js:44100
_handleDrop @ foundry.js:44151

**Comment by cswendrowski** [comment]
Closed as of 2.1.0

**Comment by GambetTV** [comment]
As far as I can tell, it still does not work.

**Comment by Glunty** [comment]
There is indeed still a problem but not the same one.

The init function that has to be executed once crashes (dragupload.js:41 Uncaught (in promise) The requested file storage s3 does not exist!). 
It does not create the setting fileUploadFolder because it crashes before, I think in await FilePicker.browse("s3", "").

And so when i dragUpload i get 
Uncaught (in promise) Error: This is not a registered game setting
[Detected 1 package: dragupload]
    at ClientSettings.get (foundry.js:2115)
    at createFoldersIfMissing (dragupload.js:71)
    at initializeDragUpload (dragupload.js:58)
    at dragupload.js:45

I have installed foundry on a AWS EC2, but haven't configured a S3 yet. (Not using ForgeVTT)

If you want me to run others tests, I'll gladly do.

**Comment by Glunty** [comment]
I opened https://github.com/cswendrowski/FoundryVTT-Drag-Upload/issues/39 to track it
